//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeluqueriaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Retirar_producto = new HashSet<Retirar_producto>();
            this.registro_tratamiento_cliente = new HashSet<registro_tratamiento_cliente>();
        }
    
        public string CUI_empleado { get; set; }
        public string Primer_nombre_empleado { get; set; }
        public string Segundo_nombre_empleado { get; set; }
        public string Primer_apellido_empleado { get; set; }
        public string Segundo_apellido_empleado { get; set; }
        public string dirección { get; set; }
        public Nullable<int> Id_rol_empleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retirar_producto> Retirar_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_tratamiento_cliente> registro_tratamiento_cliente { get; set; }
        public virtual Rol_empleado Rol_empleado { get; set; }
    }
}
