//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeluqueriaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion
    {
        public int Id_promocion { get; set; }
        public string Nombre_promocion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_inicio { get; set; }
        public System.DateTime Fecha_fin { get; set; }
        public string imagen_anuncio { get; set; }
        public Nullable<int> Id_tipo_tratamiento { get; set; }
    
        public virtual Tipo_tratamiento Tipo_tratamiento { get; set; }
    }
}
