//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeluqueriaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_tratamiento_cliente
    {
        public int Id_registro { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Costo { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public string CUI_empleado { get; set; }
        public Nullable<int> Id_tipo_tratamiento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Tipo_tratamiento Tipo_tratamiento { get; set; }
    }
}
