//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeluqueriaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_compra
    {
        public int Id_compra { get; set; }
        public System.DateTime Fecha_compra { get; set; }
        public decimal costo_unidad { get; set; }
        public int total_unidades { get; set; }
        public Nullable<int> Id_proveedor { get; set; }
        public Nullable<int> Id_insumo { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
